name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form to help us reproduce and fix the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your bug report
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I am using the latest version of the software
          required: true
        - label: I have read the troubleshooting guide
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - API Gateway
        - Job Discovery Service
        - AI Analysis Service
        - Application Engine
        - Email Manager
        - Dashboard (Frontend)
        - Database
        - Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: In which environment did this occur?
      options:
        - Development (local)
        - Docker Compose
        - Kubernetes
        - Production
        - Staging
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Screenshots
      description: Add any relevant logs, error messages, or screenshots
      placeholder: |
        Paste logs here or drag and drop screenshots...
        
        Please include:
        - Browser console logs (if frontend issue)
        - Server logs with timestamps
        - Error stack traces
        - Screenshots of the issue

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you running?
      placeholder: e.g., v1.2.3, commit hash, or Docker tag
    validations:
      required: true

  - type: textarea
    id: system_info
    attributes:
      label: System Information
      description: Please provide system details
      placeholder: |
        - OS: (e.g., Ubuntu 20.04, Windows 10, macOS 12.0)
        - Node.js version: (e.g., 18.17.0)
        - Browser: (e.g., Chrome 115.0, Firefox 116.0)
        - Docker version: (if applicable)
        - Kubernetes version: (if applicable)

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Relevant configuration (remove sensitive data)
      placeholder: |
        Please include relevant parts of your configuration:
        - Environment variables (remove API keys)
        - Docker Compose settings
        - Custom configuration files
    
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help...

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (system unusable)
        - High (major feature broken)
        - Medium (minor feature broken)
        - Low (cosmetic issue)
    validations:
      required: true